#' Paste snippet for snakemake S4 object
#'
#' Paste the snippet for constructing snakemake S4 object. The snippet is generated by [build_snakemake_s4_snippet()].
#'
#' @return Invisibly returns the inserted snippet as a character vector.
#' @export
#' @seealso [build_snakemake_s4_snippet()]
#'
#' @examples
#' insert_snakemake_s4_snippet()
insert_snakemake_s4_snippet <- function(...) {
  if (!rstudioapi::isAvailable()) {
    stop(
      "rstudioapi is not available. Run this function from within RStudio.",
      call. = FALSE
    )
  }

  defaults <- list(
    n_input = 2,
    n_output = 1,
    n_param = 1
  )

  user_args <- list(...)

  defaults[names(user_args)] <- user_args
  final_args <- defaults

  # 4. Call the 'sab' function using the final argument list
  snippet <- do.call(build_snakemake_s4_snippet, final_args)
  rstudioapi::insertText(text = snippet)
}
